### ISSUE TITLE
Install promblem Ruby 3.3.4 MacOS

### ISSUE THREAD

**Issue by MadBomber** [ankane/transformers-ruby#4]
I cannot gem install because ....

In file included from backends.cpp:5:
./utils.h:8:1: error: static assertion failed due to requirement '2 == 4': Incompatible LibTorch version

`brew` tells me that LibTorch has been renamed to PyTorch.  I have the latest version according to brew of pytorch installed.

15:24:59 3.3.4 v20.15.0  nibiru:~ $ brew search libtorch
==> Formulae
libotr
Warning: Formula libtorch was renamed to pytorch.

15:25:42 3.3.4 v20.15.0  nibiru:~ $ brew install pytorch
Warning: pytorch 2.2.0_9 is already installed and up-to-date.
To reinstall 2.2.0_9, run:
  brew reinstall pytorch
15:26:11 3.3.4 v20.15.0  nibiru:~ $ brew reinstall pytorch
==> Downloading https://ghcr.io/v2/homebrew/core/pytorch/manifests/2.2.0_9
Already downloaded: /Users/dewayne/Library/Caches/Homebrew/downloads/a8b6189c63b5dda8142cbe90582ecb48b088743bf062367ea8af82fdc40d4b7d--pytorch-2.2.0_9.bottle_manifest.json
==> Fetching pytorch
==> Downloading https://ghcr.io/v2/homebrew/core/pytorch/blobs/sha256:ad2daff320c5a9944016490437
Already downloaded: /Users/dewayne/Library/Caches/Homebrew/downloads/11aea6da242cd4f0a3756ea3298ec59a6f9acc0d1e24ea7e81ca99be2765eeb5--pytorch--2.2.0_9.arm64_sonoma.bottle.tar.gz
==> Reinstalling pytorch
==> Pouring pytorch--2.2.0_9.arm64_sonoma.bottle.tar.gz
🍺  /opt/homebrew/Cellar/pytorch/2.2.0_9: 13,168 files, 240.7MB
==> Running `brew cleanup pytorch`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).

This the the attempt at the gem install ....

15:11:17 3.3.4 v20.15.0  nibiru:~ $ gem ins transformers-rb
Fetching transformers-rb-0.1.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing transformers-rb:
	ERROR: Failed to build gem native extension.

    current directory: /Users/dewayne/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/torch-rb-0.17.1/ext/torch
/Users/dewayne/.rbenv/versions/3.3.4/bin/ruby extconf.rb
checking for rice/rice.hpp in /Users/dewayne/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/rice-4.3.1/include... yes
checking for -lc++... yes
checking for -ltorch... yes
checking for -lmkldnn... no
checking for -lnnpack... no
Generating C++ functions...
creating Makefile

current directory: /Users/dewayne/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/torch-rb-0.17.1/ext/torch
make DESTDIR\= sitearchdir\=./.gem.20240908-7934-k0r5jh sitelibdir\=./.gem.20240908-7934-k0r5jh clean

current directory: /Users/dewayne/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/torch-rb-0.17.1/ext/torch
make DESTDIR\= sitearchdir\=./.gem.20240908-7934-k0r5jh sitelibdir\=./.gem.20240908-7934-k0r5jh
compiling backends.cpp
In file included from backends.cpp:5:
./utils.h:8:1: error: static assertion failed due to requirement '2 == 4': Incompatible LibTorch version
static_assert(
^
1 error generated.
make: *** [backends.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dewayne/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/torch-rb-0.17.1 for inspection.
Results logged to /Users/dewayne/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/torch-rb-0.17.1/gem_make.out
15:15:20 3.3.4 v20.15.0  nibiru:~ $

**Comment by ankane** [comment]
Hi @MadBomber, the latest version of Torch.rb requires LibTorch 2.4 (Homebrew is currently on 2.2). See the [installation instructions](https://github.com/ankane/torch.rb?tab=readme-ov-file#installation) for how to get it.

**Comment by MadBomber** [comment]
Thanks.  btw neighbor made a significant impact on a time critical project last week.  We had basically 4 days to implement a pilot project.  We met the deadline!

**Comment by ankane** [comment]
Awesome, great to hear!
